# Module manifest for module 'osquery'
# Generated by: skatterbrainz
# Generated on: 12/02/2025
# Updated on: 05/08/2026

@{
	RootModule = 'osquery.psm1'
	ModuleVersion     = '2.1.0'
	# CompatiblePSEditions = @()
	GUID              = 'db1ebc51-18f4-4257-b8de-37092fdbe2c3'
	Author            = 'David Stein'
	#CompanyName       = 'skatterbrainz'
	Copyright         = '(c) David Stein. All rights reserved.'
	Description       = 'A PowerShell module for interacting with osquery.'
	PowerShellVersion = '7.0'
	# PowerShellHostName = ''
	# PowerShellHostVersion = ''
	# DotNetFrameworkVersion = ''
	# ClrVersion = ''
	# ProcessorArchitecture = ''
	# RequiredModules = @()
	# RequiredAssemblies = @()
	# ScriptsToProcess = @()
	# TypesToProcess = @()
	# FormatsToProcess = @()
	# NestedModules = @()
	FunctionsToExport = @(
		"Disable-OsQueryDaemon",
		"Enable-OsQueryDaemon",
		"Get-OsQueryCertificates",
		"Get-OsQueryCronJobs",
		"Get-OsQueryDaemonStatus",
		"Get-OsQueryDisk",
		"Get-OsQueryDockerContainers",
		"Get-OsQueryFiles",
		"Get-OsQueryFirewall",
		"Get-OsQueryGroups",
		"Get-OsQueryInstalledPackages",
		"Get-OsQueryIPAddress",
		"Get-OsQueryLoggedInUsers",
		"Get-OsQueryNetworkConnections",
		"Get-OsQueryProcesses",
		"Get-OsQuerySchema",
		"Get-OsQueryServices",
		"Get-OsQuerySudoers",
		"Get-OsQuerySystemInfo",
		"Get-OsQueryTableSample",
		"Get-OsQueryUsers",
		"Invoke-OsQueryTableQuery",
		"New-OsQueryConfig",
		"Show-OsQueryInstall",
		"Test-OsQueryInstall"
	)
	CmdletsToExport   = @()
	VariablesToExport = @()
	AliasesToExport   = @(
		"Disable-OsQueryService",
		"Enable-OsQueryService",
		"Get-OsQueryServiceStatus"
	)
	# DscResourcesToExport = @()
	# ModuleList = @()
	# FileList = @()
	PrivateData       = @{
		PSData = @{
			Tags = @("osquery","powerShell","inventory","query","database","sql","hardware","cim","wmi","skatterbrainz")
			LicenseUri = 'https://github.com/Skatterbrainz/osquery/blob/main/LICENSE'
			ProjectUri = 'https://github.com/Skatterbrainz/osquery'
			# IconUri = ''
			# ReleaseNotes = ''
			# Prerelease = ''
			# RequireLicenseAcceptance = $false
			# ExternalModuleDependencies = @()
		} # End of PSData hashtable
	} # End of PrivateData hashtable
	# HelpInfoURI = ''
	# DefaultCommandPrefix = ''
}