# Module manifest for module 'osquery'
# Generated by: skatterbrainz
# Generated on: 10/5/2025

@{
	RootModule = 'osquery.psm1'
	ModuleVersion     = '1.0.0'
	# CompatiblePSEditions = @()
	GUID              = 'db1ebc51-18f4-4257-b8de-37092fdbe2c3'
	Author            = 'skatterbrainz'
	CompanyName       = 'skatterbrainz'
	Copyright         = '(c) skatterbrainz. All rights reserved.'
	Description       = 'A PowerShell module for interacting with osquery.'
	# PowerShellVersion = ''
	# PowerShellHostName = ''
	# PowerShellHostVersion = ''
	# DotNetFrameworkVersion = ''
	# ClrVersion = ''
	# ProcessorArchitecture = ''
	# RequiredModules = @()
	# RequiredAssemblies = @()
	# ScriptsToProcess = @()
	# TypesToProcess = @()
	# FormatsToProcess = @()
	# NestedModules = @()
	FunctionsToExport = @("Get-*","Invoke-*","Test-*")
	CmdletsToExport   = @()
	VariablesToExport = '*'
	AliasesToExport   = @()
	# DscResourcesToExport = @()
	# ModuleList = @()
	# FileList = @()
	PrivateData       = @{
		PSData = @{
			Tags = @("osquery","powerShell","skatterbrainz")
			# LicenseUri = ''
			# ProjectUri = ''
			# IconUri = ''
			# ReleaseNotes = ''
			# Prerelease = ''
			# RequireLicenseAcceptance = $false
			# ExternalModuleDependencies = @()
		} # End of PSData hashtable
	} # End of PrivateData hashtable
	# HelpInfoURI = ''
	# DefaultCommandPrefix = ''
}